# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy JAR app to Azure Web App - FedeganAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Prepare deployment package
        run: |
          # Crear la estructura del deployment
          mkdir -p deployment
          # Copiar el JAR con un nombre fijo para fácil referencia
          cp build/libs/*.jar deployment/app.jar
          # Copiar archivos de New Relic
          mkdir -p deployment/newrelic
          cp -r src/main/java/com/example/fedegan/newrelic/* deployment/newrelic/
          
          # Crear script .bat para Windows (Azure App Service usa Windows)
          cat > deployment/startup.bat << 'EOL'
          @echo off
          echo Starting application with New Relic agent
          echo Current directory:
          cd
          echo Files in newrelic directory:
          dir D:\home\site\wwwroot\newrelic
          
          java -javaagent:"D:\home\site\wwwroot\newrelic\newrelic.jar" -jar "D:\home\site\wwwroot\app.jar"
          EOL
          
          # Hacer el script ejecutable (no necesario para .bat)
          
          # Crear archivo web.config para Azure App Service
          cat > deployment/web.config << 'EOL'
          <?xml version="1.0" encoding="UTF-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
              </handlers>
              <httpPlatform processPath="%HOME%\site\wwwroot\startup.bat"
                            arguments=""
                            stdoutLogEnabled="true"
                            stdoutLogFile="%HOME%\LogFiles\stdout">
              </httpPlatform>
            </system.webServer>
          </configuration>
          EOL

      - name: Create ZIP package
        run: cd deployment && zip -r ../deployment.zip *

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: java-app-zip
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-zip
      
      - name: Display structure of downloaded files
        run: unzip -l deployment.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80EABB6B9A3446308F6FB31A6EA627FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B48AF1FC5134E3197572B01AC9D8732 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D9109122A0DB4A7B86DC33ACED6BEE55 }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FedeganAPI'
          slot-name: 'Production'
          package: deployment.zip
          
      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'FedeganAPI'
          app-settings-json: '[
            {
              "name": "JAVA_TOOL_OPTIONS", 
              "value": "-javaagent:D:\\home\\site\\wwwroot\\newrelic\\newrelic.jar", 
              "slotSetting": false
            },
            {
              "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE", 
              "value": "true", 
              "slotSetting": false
            }
          ]'